export const authConstants = {
	REGISTER_STARTED: 'REGISTER_STARTED',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_ERROR: 'REGISTER_ERROR',
	LOGIN_STARTED: 'LOGIN_STARTED',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_ERROR: 'LOGIN_ERROR',
	FORGOT_STARTED: 'FORGOT_STARTED',
	FORGOT_SUCCESS: 'FORGOT_SUCCESS',
	FORGOT_ERROR: 'FORGOT_ERROR',
	LOGOUT_STARTED: 'LOGOUT_STARTED',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_ERROR: 'LOGOUT_ERROR',
};
export default authConstants;
