export const bakeryConstants = {
	CREATE_STARTED: 'CREATE_STARTED',
	CREATE_SUCCESS: 'CREATE_SUCCESS',
	CREATE_ERROR: 'CREATE_ERROR',
	GET_BAKERIES_STARTED: 'GET_BAKERIES_STARTED',
	GET_BAKERIES_SUCCESS: 'GET_BAKERIES_SUCCESS',
	GET_BAKERIES_ERROR: 'GET_BAKERIES_ERROR',
};
export default bakeryConstants;
