export const userConstants = {
	GET_USERS_STARTED: 'GET_USERS_STARTED',
	GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
	GET_USERS_ERROR: 'GET_USERS_ERROR',
	GET_USER_STARTED: 'GET_USER_STARTED',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_ERROR: 'GET_USER_ERROR',
	UPDATE_USER_STARTED: 'UPDATE_USER_STARTED',
	UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
	UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
	DELETE_USER_STARTED: 'DELETE_USER_STARTED',
	DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
	DELETE_USER_ERROR: 'DELETE_USER_ERROR',
};
export default userConstants;
